apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: ${k8s_user_arn}
      username: ${k8s_user}
      groups:
        - system:masters

